adaptlearning/adapt-cli

- lib/promise/install.js
- on *nix, requirejs throws an error due to case sensitivity in paths
> fix #32 - fix error "cannot find module 'Q'"

- .travis.yml
- README.md
- now only allow to build below branch names (case sensitive) on Travis
- master
- develop
- now limiting to ```depth: 10``` while cloning git repository
- caching ```node_modules``` directory content
- integrating with Gitter for notifications
> Travis enhancement

- lib/PackageMeta.js
- lib/commands/devinstall.js
- lib/promise/cloneInstall.js
- package.json
This is a bit speculative.
I wanted a way to get the framework and all the bundled plugins checked out as git repos so I could do a bit of development. The `adapt install [x]` and `adapt create course` commands didn't give a git repo that I could add my fork as a remote to.
This devinstall command will clone the adapt_framework and all the plugins defined in adapt.json as git repos allowing you to get going faster.
Run it as `adapt devinstall` to create an adapt_framework repo in your current directory.
It should run ok from within a previously created adapt_framework directory.
You can install a single plugin via `adapt devinstall [pluginname]` from within `_root/adapt_framework` or `_root/`
> Devinstall command for cli tool

- lib/Constants.js
- lib/commands/register.js
- lib/commands/unregister.js
To avoid the situation where a missing `.bowerrc` results in bower using its default registry (`bower.herokuapp.com`) the code has been amended so that the CLI determines the registry by first checking for the `ADAPT_REGISTRY` environment variable, then attempting to read the property`registry` from `.bowerrc`, before falling back to a constant `adapt-bower-repository.herokuapp.com`.
> Target registry consistently (envvar>.bowerrc>constant)

- lib/VersionChecker.js
- test/specs/installing_incompatible_plugins_concerns.js
Resolves repeated erroneous warnings about plugin compatibility with Adapt when using commands such as:
`adapt create course` and `adapt install`
> Fix for #76

- lib/PackageMeta.js
`getRepositoryUrl` was attempting to search bower using `name#>=version` when it should just be `name`.
Resolves #83.
> issue/#83 : fixed getRepositoryUrl for devinstall

- README.md
- lib/commands/register.js
- package.json
@moloko mind having a quick look/test and let me know who else might be a good candidate for verification?
> Fixes for issues #110 and #111

- lib/Constants.js
- lib/cli.js
- lib/commands/install.js
- lib/commands/install/InstallTarget.js
- lib/commands/uninstall.js
- lib/commands/update.js
- lib/errors.js
- lib/promise/install.js
- lib/promise/uninstallPackage.js
@chris-steele kindly put the work in earlier this year to expose some of the CLI's commands as an API.
The rewrite of the authoring tool utilises this API.
This PR implements the first three commands from this [page](https://github.com/adapt-security/adapt-authoring/wiki/CLI-requirements).
> Expose commands as an API

- lib/commands/install.js
Resolves #139.
Fun fact: this functionality is already in use by the unreleased authoring tool.
As usual, not going for a syntactical refactor; the code style has been copied and modified from existing functions <img src=https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/whatsapp/273/smiling-face-with-tear_1f972.png height=20 width=20>.
> Add logic for compatible newer (pre-release) tags

- lib/integration/AdaptFramework/build.js
fixes https://github.com/adapt-security/adapt-authoring/issues/517
* Handle outputs without `Error` in stdout.
> issue/517 Fixed missing matches in stdout

- lib/econnreset.js
#169 
* Remove process.exit from uncaught exception handler
> Fix: Remove process.exit from uncaught exception

- lib/integration/Plugin.js
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
https://github.com/adaptlearning/adapt-cli/issues/183
> Fix: Pass semverOptions to satisfies in Plugin.hasValidRequestVersion

- lib/api.js
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
#185
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
API additions:
* **updateFramework**: pulls latest version of the framework & updates installed plugins where possible.
* **getCurrentFrameworkVersion**: returns the installed framework version.
[//]: # (Mention any other dependencies)
> New: add update API (fixes #185)

- lib/integration/AdaptFramework/erase.js
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
#193
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* Have amended the delete action to remove the root folder only (the recursive option takes care of the rest).
[//]: # (List appropriate steps for testing if needed)
Currently only replicable by running an install over an existing install - not sure if this is possible via the CLI.
[//]: # (Mention any other dependencies)
> Fix: error thrown on recursive delete (fixes #193)

- lib/integration/Target.js
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)
[//]: # (Link the PR to the original issue)
#196 
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* Target to use packageName rather than name on install (fixes #196)
> Fix: target to use packageName rather than name on install (#196)

- lib/logger.js
fixes #198 
* Logger error and warn output is correctly written to the console
> Fix: Logger error and warn output (fixes #198)

- lib/integration/PluginManagement/register.js
fixes #200 
* Allow register of private repos
> Fix: Allow register of private repos (fixes #200)

- lib/integration/Plugin.js
- lib/integration/PluginManagement/update.js
fixes #180 
* Added guard to property lookup
* Prevent asking user to pick update pathways where there are none
> Fix: Missing sourceinfo causes property lookup on undefined object

- lib/commands/create.js
Fix #207 
* Change the order of `adapt create course` steps to put `branch/tag` step before `name` step.
Run `adapt create course`. You should see the steps in this order:
```
? type: course
? branch/tag v5.40.6
? name (my-adapt-course)
```
> Update: Change order of adapt create course steps to put branch/tag before course (fix #207)

- .github/pull_request_template.md
- lib/integration/PluginManagement/update.js
Fixes #206 
* Fix typo in _.github/pull_request_template.md_
* Show current version plus latest compatible version in dry runs
1. Run `adapt update --check`. The version first listed should be the current:
```
adapt-contrib-narrative 7.4.11 (latest compatible version is 7.8.0)
```
> Update: Show current version plus latest compatible version in dry runs (fixes #206)

- lib/integration/AdaptFramework/npmInstall.js
#211 
* Add required spawn parameter for Node on Windows
> Fix: add required spawn parameter for Node on Windows (fixes #211)

- lib/commands/create.js
- lib/commands/create/extension.js
- lib/util/constants.js
fixes #216 
* Added extension to create options
> Fix: Added missing adapt create extension (fixes #216)

- lib/integration/Plugin.js
#219 
[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
* Prevent error when local plugin not found
> Fix: prevent error when local plugin not found (fixes #219)
